# docker-compose.test.yml
version: '3.9'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_ENV=test
    environment:
      - PYTHONPATH=/app
      - TESTING=true
    volumes:
      - ./app:/app:ro
      - ./modules:/app/modules:ro
      - ./tests:/app/tests:ro
    command: pytest -v --cov=/app --cov-report=term-missing tests/